### PR TITLE
fix: Update sidenav to allow selected top item to open/close

### LINKED ISSUE #71: Accordion in left nav does not collapse when second level nav item is selected
**Steps to reproduce**

- On [staging site](https://next.carbondesignsystem.com/guidelines/content/general)
- Click on Guidelines
- Select Accessability
- Try to collapse Guidelines.
(this happens on all sections - not just guidelines and accessibility)

**Expected result:**
Guidelines collapses

**Actual results:**
Guidelines stays open

screen shot 2018-09-20 at 8 53 41 am

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #71

Also adds focus states to the nav and updates the click element to be a button instead of an a tag with no link.

### CODE REVIEW

File: src/components/SideNav/SideNavItem.js [hunk 1]
```diff
@@ -48,24 +47,31 @@ export default class SideNavItem extends React.Component {
...
+  };
+   
   render() {
     const { item, itemSlug } = this.props;
     const hasSubNav = !(item['sub-nav'] === undefined);
 
     return (
       <Location>
         {({ location }) => {
+          //console.log('retrn location', location);
```
Comment (asudoh) [inline src/components/SideNav/SideNavItem.js]: Did you mean to remove this line!

Comment (alisonjoseph) [reply src/components/SideNav/SideNavItem.js]: Yes, will remove. thanks!

**Comment by alisonjoseph** [comment]
Shouldn't conflict with @lovemecomputer s updates, however need to sync up with DA on his updates.
