### PR TITLE
search bug fixes

### LINKED ISSUE #123: Side nav jumps when "Components" are expanded
## Detailed description
The spacing between "About Carbon" and the search field changes when the component section is expanded.

> What did you expect to happen? What happened instead? What would you like to see changed?
Spacing should be consistent

> What browser are you working in?
Chrome and Safari - It works in Firefox

screen shot 2018-09-26 at 12 48 24 pm
screen shot 2018-09-26 at 12 53 32 pm

### LINKED ISSUE #129: Search hidden / sidebar overflow issue
check overflow on sidebar, this was working, some recent PR must have broken it

screen shot 2018-09-26 at 5 49 44 pm

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #129 
closes #123 

and fixes spacing on content page w/ images

### CODE REVIEW

File: src/components/GlobalSearch/GlobalSearch.js [hunk 1]
```diff
@@ -14,7 +14,8 @@ export default class GlobalSearch extends React.Component {
       apiKey: `296ea0c1d0e96b2b04900d0f4d1a6329`,
       indexName: `carbondesignsystem`,
       inputSelector: `#doc-search`,
-      debug: false,
+      //set this to true if you need to debug css
+      debug: true,
```
Comment (joshblack) [inline src/components/GlobalSearch/GlobalSearch.js]: Should this be off in the merged commit?

Comment (alisonjoseph) [reply src/components/GlobalSearch/GlobalSearch.js]: yup
